sudo: required

language: python
python:
  - 2.7

services:
  - docker

before_install:
  - docker build -t bluemixcode/node-xvfb .
  - docker run -d --name xvfb xvfb

script:
  - docker ps | grep -q xvfb
